### ISSUE TITLE
请问模型文件在哪里呢

### ISSUE THREAD

**Issue by freemanxzx** [thunlp/THUCKE#1]
1.下载模型文件（下载地址）：

将模型下载并解压到./res/，解压后目录结构应为：

文中的模型下载地址直接跳贵校实验室主业了：http://thucke.thunlp.org/site2/index.php/zh，请问模型文件在哪里呢

**Comment by mysbupt** [comment]
刚刚模型下载页面出现了一些问题，现在已经修复可以继续下载了。多谢反馈！
