### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Wander0110** [thunlp/THUCKE#9]
您好，请问可以提供训练时用的网易新闻数据集嘛？

**Comment by Kong-Aobo** [comment]
Can the dataset be open source?

**Comment by zibuyu** [comment]
Hi,

The dataset can be downloaded here: http://114.215.64.60/~lzy/datasets/163_chinese_news_dataset_2011.zip

**Comment by zibuyu** [comment]
Hi,

The dataset can be downloaded here: http://114.215.64.60/~lzy/datasets/163_chinese_news_dataset_2011.zip
